const Colors = {
    primary: {
        main: '#FF6000',
        brandPrimary: '#FF6000',
        blue: '#0976C8',
        red: '#E02020',
        brandYellow: '#FF9F2F',
        yellow: '#FABE2C',
        brandingYellow: '#FFF521',
        orange: '#FAA82C',
    },
    secondary: {
        brandSecondary: '#321AF1',
        surfaceSecondary: '#F3F3F3',
        surfaceButton: '#E0DFDF',
        iconInactive: '#F0EBE8',
        iconActive: '#FF6000',
        iconGeneral: '#BAA697',
        button: '#97B4DC',
        background: '#F8F7F6',
        darkerBackground: '#E5E5E5',
        border: '#EDEDED',
        borderDarker: '#D8D8D8',
        lightBackground: '#FBFAFA',
        inputBackground: '#F3F3F3',
        buttonBackground: '#FCFEFF',
        buttonBackground2: '#B9B1AA',
        blurBackground: '#29120166',
        errorBackground: '#FAF6F6',
        likesBorder: '#F8F8F8',
        myMessageBackground: '#FF6000',
        whiteSnow: '#FCFCFC',
        surfaceBeige: '#F8F7F6',
        silver: '#939393',
        bronze: '#913C09',
        blackBackground: '#0E0F18',
        brownDark: '#44403D',
        profileBackground: '#FDFBFA',
        tertiaryButton: '#EEE9E6',
    },
    text: {
        primary: '#131415',
        secondary: '#868078',
        tertiary: '#BAA697',
        tertiaryLight: '#E0D8D2',
        caption: '#767A80',
        success: '#5CC689',
        error: '#FA6434',
        gray: '#515559',
        calendarBlack: '#2E2E39',
        middleGray: '#6D7278',
        lightGray: '#7D848D',
        extraLightGray: '#A2A9B2',
        brown: '#858079',
        brownLighter: '#8F6F57',
        placeholder: '#D3C2C2',
        lightBlue: '#007AFF',
        myMessageLink: '#7ABEF1',
        grayBlack: '#333333',
        darkGrayish: '#293137',
        darkGray: '#6D7275',
    },
    basic: {
        black: '#000000',
        white: '#FFFFFF',
        gray: '#ADADAD',
        red: '#D10000',
    },
    modal: {
        background: '#F5F5F5',
        borderDivider: '#E5E5EA',
        closeBG: '#E7E6E8',
        backgroundSecond: '#DBDBDB',
        indicator: '#ECE4DF',
        banner: '#F7F3F0BF',
    },
};

export default Colors;